server {
    listen 80;

    # Ruch do Flaska (Zadanie 1)
    location /flask/ {
        rewrite ^/flask/(.*) /$1 break;
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Ruch do FastAPI (Zadanie 2)
    location /fastapi/ {
        rewrite ^/fastapi/(.*) /$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}